export const SUPPORTED_LANGUAGES = {
  'zh-HK': { name: 'Cantonese', flag: '🇭🇰' },
  'nl-NL': { name: 'Dutch', flag: '🇳🇱' },
  'en-US': { name: 'English', flag: '🇺🇸' },
  'fr-FR': { name: 'French', flag: '🇫🇷' },
  'fr-CA': { name: 'French (Canada)', flag: '🇨🇦' },
  'de-DE': { name: 'German', flag: '🇩🇪' },
  'hi-IN': { name: 'Hindi', flag: '🇮🇳' },
  'it-IT': { name: 'Italian', flag: '🇮🇹' },
  'ja-JP': { name: 'Japanese', flag: '🇯🇵' },
  'ko-KR': { name: 'Korean', flag: '🇰🇷' },
  'zh-CN': { name: 'Mandarin (Simplified)', flag: '🇨🇳' },
  'zh-TW': { name: 'Mandarin (Traditional)', flag: '🇹🇼' },
  'ms-MY': { name: 'Malay', flag: '🇲🇾' },
  'nb-NO': { name: 'Norwegian', flag: '🇳🇴' },
  'pl-PL': { name: 'Polish', flag: '🇵🇱' },
  'pt-PT': { name: 'Portuguese', flag: '🇵🇹' },
  'pt-BR': { name: 'Portuguese (Brazil)', flag: '🇧🇷' },
  'ru-RU': { name: 'Russian', flag: '🇷🇺' },
  'es-ES': { name: 'Spanish (Spain)', flag: '🇪🇸' },
  'es-MX': { name: 'Spanish (Mexico)', flag: '🇲🇽' },
  'sv-SE': { name: 'Swedish', flag: '🇸🇪' },
  'ta-IN': { name: 'Tamil', flag: '🇮🇳' },
  'th-TH': { name: 'Thai', flag: '🇹🇭' },
  'vi-VN': { name: 'Vietnamese', flag: '🇻🇳' },
} as const;

export type LanguageCode = keyof typeof SUPPORTED_LANGUAGES;